[package]
authors = ["Hironori Yamamoto <mr.nikoru918@gmail.com>"]
edition = "2018"
name = "portfolio"
version = "0.1.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
once_cell = "1.7.2"
yew = "0.17"
